#@API_URL={{$dotenv PRODUCTION_API}}

@API_URL = http://localhost:8080

GET {{API_URL}}/notes

###

GET {{API_URL}}/notes/4

###

POST http://localhost:8080/notes
Content-Type: application/json

{
    "note": "POST funkar!"
}

###

PUT http://localhost:8080/notes/2
Content-Type: application/json

{
    "note": "konffa prisma"
}
###

DELETE http://localhost:8080/notes/2
