#@API_URL={{$dotenv PRODUCTION_API}}

@API_URL = http://localhost:3001

@DEV_TOKEN = {{$dotenv DEV_TOKEN}}

GET {{API_URL}}/notes

###

GET {{API_URL}}/notes/4
Authorization: Bearer {{DEV_TOKEN}}

###

POST http://localhost:8080/notes
Content-Type: application/json

{
    "note": "POST funkar!"
}

###

PUT http://localhost:8080/notes/2
Content-Type: application/json

{
    "note": "konffa prisma"
}
###

DELETE http://localhost:8080/notes/2
